### ISSUE TITLE
gmp-freestanding, zarith-freestanding: Update to build with SSP, disable any use of -fPIC

### ISSUE THREAD

**Issue by mato** [mirage/ocaml-freestanding#47]
Reporting this here as the OPAM `gmp-freestanding` and `zarith-freestanding` packages don't have an associated issue tracker, and I don't want to spam Solo5/solo5#294 with this.

The changes in Solo5/solo5#294 break `gmp-freestanding` due to issues with its cross-compiling hacks. While fixing this, I also found that `-fPIC` was not being disabled correctly, so I fixed that as it will come in handy with other upcoming Solo5 changes that will alter the build toolchain used for `ocaml-freestanding`. This in turn broke `zarith-freestanding`, which has even more cross-compiling hacks, so I added some more hacks and forcibly eradicated any use of dynlink/`-fPIC` there as well.

The fixed packages are in https://github.com/Solo5/opam-solo5/commit/d13221350c7ba7b0ece978629b11c88e0f4d45ad.

@hannesm When you have a moment, could you verify that pinning Solo5/solo5#294 and the versions of gmp-freestanding, zarith-freestanding above gets you a set of packages that successfully builds a unikernel that uses them? (i.e. one using `tls`) I have tested this on Debian, but would like a 2nd pass on FreeBSD.

I'm not sure what to do for conflicts/depends on these packages:

Once a version of Solo5 with SSP is released, `gmp-freestanding` needs to be at least `6.1-2`. Does that mean I should add a `conflicts:` on all older versions at that point? The `zarith-freestanding` update is fine as it explicitly depends on the newer `gmp-freestanding`, however, technically, older versions of `zarith-freestanding` will fail with the newer `gmp-freestanding` due to the PIC-disabling going on.

**Comment by hannesm** [comment]
@mato tested your repository with solo5 pinned to mato/solo5.git#zeropage - it compiles fine, and an example tls client (the unikernel in `ocaml-tls/mirage/example` with `setenv BUILD client`) is able to do bignum arithmetics.

conflicts/depends: all in opam-repository released zarith-freestanding need an upper bound `"gmp-freestanding" {<= "6.1.2-1"}`.

**Comment by mato** [comment]
> @mato tested your repository with solo5 pinned to mato/solo5.git#zeropage - it compiles fine, and an example tls client (the unikernel in `ocaml-tls/mirage/example` with `setenv BUILD client`) is able to do bignum arithmetics.

@hannes: Sorry, I should have been explicit rather than referring to PR
numbers. Please test against https://github.com/mato/solo5#ssp, not #zeropage.

**Comment by hannesm** [comment]
@mato tested with your ssp as well, same result!

**Comment by mato** [comment]
@hannesm:

> conflicts/depends: all in opam-repository released zarith-freestanding need an upper bound "gmp-freestanding" {<= "6.1.2-1"}.

Right, but I also need to somehow reflect that the current gmp-freestanding (<= 6.1.2-2) will not build with "the release of Solo5 with SSP" (for the purposes of this exercise, say, 0.5.0). At the same time, I don't want to have gmp-freestanding depend on the various solo5-bindings-* packages. The only way I can think of doing this right now is:

1. Release Solo5 (say, 0.5.0), enabling SSP.
2. Release ocaml-freestanding (say, also 0.5.0 to be consistent), with no changes except a new version number, and have it depend on solo5-bindings-* >= 0.5.0.
3. Release gmp-freestanding 6.1.2-2, depending on ocaml-freestanding >= 0.5.0.
4. Release zarith-freestanding 1.7-1, depending on gmp-freestanding >= 6.1.2-2, and as you mentioned add upper bounds on gmp_freestanding <= 6.1.2-1 to existing releases.

I shouldn't need to add upper bounds to existing releases of gmp-freestanding as the new one will build fine with the older ocaml-freestanding/Solo5.

Does this make sense?

**Comment by hannesm** [comment]
@mato this makes sense to me, although I'd move the `upper bounds` item to the front. keep in mind that https://github.com/mirage/mirage/pull/855 resulted in all unikernels having upper bounds (`< 0.5.0`) for solo5-bindings-* packages (and `< 0.6.0` for mirage-solo5).

**Comment by mato** [comment]
@hannesm Thanks for confirming. Given the state of various open issues and the scope of the recent hardening changes on `master`, I'm not going to rush with a Solo5 release right now. It'd be good to get some more thorough testing of Solo5 `master` against Mirage, which can be done with the versions of gmp-freestanding and zarith-freestanding that are in the Solo5/opam-solo5 repository now.

Let's discuss next week when you're back from travels.

**Comment by mato** [comment]
Fixed by ocaml/opam-repository#13279
