### ISSUE TITLE
How to add support for <inttypes.h>

### ISSUE THREAD

**Issue by emillon** [mirage/ocaml-freestanding#60]
Hello,

I'm trying to build a library that uses `<inttypes.h>`, more specifically it's in [`hacl`](https://github.com/mirage/hacl/blob/54edddf123bd79861a9c76b053ddd6739ba9cc69/src/kremlib_base.h#L26) - the `PRIu64` macro [is used](https://github.com/mirage/hacl/blob/54edddf123bd79861a9c76b053ddd6739ba9cc69/src/kremlib.h#L446) - it should expand to a format string specifier. This C99 header are unfortunately not supported in `ocaml-freestanding`.

In this particular case I might be able to patch my way around this problem (this debug code can be stripped), but this is not ideal as this code is extracted, so I'd rather not touch it too much.

How would I go about adding support for `<inttypes.h>`? can I just add `inttypes.h` in `nolibc/include/`?

(same would apply to `bswap64` - I recall adding it to a couple libraries because it was missing in freestanding)

Thanks!

**Comment by dinosaure** [comment]
Where it's mostly used to print something in the C side, I'm not very convince to add `inttypes.h` just for that. A better idea (according the fact that this file is generated), IHMO, should be to fake `PRIu64` with something else by the `-D` option or another header C file. `ocaml-freestanding` should be smallest as we can.

**Comment by mato** [comment]
@emillon:

musl [inttypes.h](http://git.musl-libc.org/cgit/musl/tree/include/inttypes.h) depends on a fair bit of libc "infrastructure", however all we would support from it are the printf format string macros. So, as a minimum, you'd need to replace the `#if UINTPTR_MAX == UINT64_MAX` block with some `#if` logic that compiles correctly on the architectures we support.

As @dinosaure says, in general we want to keep ocaml-freestanding as small as possible, so it may be better to disable the offending code (given that it's just for debug), or patch the source to add some `#defines`.
