### ISSUE TITLE
Compilation fail into a Docker container (bubblewrap)

### ISSUE THREAD

**Issue by dinosaure** [mirage/ocaml-freestanding#69]
Currently, with Ubuntu 18.06 as the initial Docker container and OPAM > 2.0.0 with `bubblewrap`, it's not possible to install properly `ocaml-freestanding`. I did not find a solution to fix that yet (I tried `OPAM_USER_PATH_RO`, only available with OPAM > 2.1.0) than a first `opam init --disable-sandboxing` command.

**Comment by hannesm** [comment]
what is the error? why is this an ocaml-freestanding problem (does it read from/write to a location/file it should not)?

**Comment by dinosaure** [comment]
It seems fine if we take `Dockerfile` provided by @avsm but a vanilla Ubuntu 18.06 give me this error:
```
ERROR: No supported Solo5 bindings package found.
ERROR: solo5-bindings-hvt, solo5-bindings-spt, solo5-bindings-virtio, solo5-bindings-muen, or solo5-bindings-genode must be installed.
```

However, in my case, `solo5-bindings-hvt` is installed the the `*.pc` file is available into `$(opam config var prefix)/lib/pkgconfig`. I'm not really aware about `bubblewrap` but I can try to provide a `Dockerfile` to reproduce the error as soon as possible.

**Comment by mato** [comment]
@dinosaure 

As far as I can tell, I've been using `bwrap` for sandboxing on Debian since it was enabled by default and have not seen any problems. (Confirmed by the presence of the relevant `wrap-XXX-commands` lines in my `.opam/config).

> I'm not really aware about bubblewrap but I can try to provide a Dockerfile to reproduce the error as soon as possible.

Yes. Please provide a full `Dockerfile` and the _full_ output of a failing build as an attachment. Without this I can't help much.

**Comment by dinosaure** [comment]
I tried to redo my process with a `Dockerfile` and simulate as much as possible sandboxing with:

```sh
$ docker run -it --rm --privileged --cap-add=CAP_SYS_ADMIN ocaml/opam2:ubuntu-18.04
# rm -r ~/.opam
# rm ~/.opamrc
# sudo sysctl kernel.unprivileged_userns_clone=1
# opam init
# opam install lwt
```

But I can not reproduce the bug. I think, the context is close to ocsigen/lwt#761 but, again, I'm not able to reproduce it.
