### ISSUE TITLE
could endian.h be enhanced with htobe64 and be64toh

### ISSUE THREAD

**Issue by hannesm** [mirage/ocaml-freestanding#71]
these primitives are needed for mirage-crypto

(e.g. from https://github.com/dune-universe/ocaml-nocrypto/commit/3d7bdd58fe8b46d7d14732e8dbe6e8a0ede0d306):
```C
#if (BYTE_ORDER == LITTLE_ENDIAN)
#define htobe64(x) (_bswap64(x))
#define be64toh(x) (_bswap64(x))
#elif (BYTE_ORDER == BIG_ENDIAN)
#define htobe64(x) (x)
#define be64toh(x) (x)
#else
#error "Cannot determine byte order"
#endif
```

**Comment by hannesm** [comment]
further investigation shows that on FreeBSD and OpenBSD the solo5 configure script copies sys/endian.h (and friends, machine/endian.h, x86/endian.h) into the include directory already (which may have an impact on this request).

**Comment by hannesm** [comment]
and this is not very high priority - there's an implementation already in a separate file of mirage-crypto. though, I think it would be sensible to have the "full" endian.h supported by freestanding, especially the little-and-big-endian-to-host conversions, plus defining BYTE_ORDER:
```C
htobe16
htobe32
htobe64
htole16
htole32
htole64

be16toh
be32toh
be64toh
le16toh
le32toh
le64toh
```

**Comment by mato** [comment]
The way to do this would be to port the relevant bits from musl, since that is what nolibc is primarily based on. Given that you have mentioned here and elsewhere that this is not a priority for you / you have other ways of accomplishing the same result, I'm not going to look at this for the next release.

**Comment by hannesm** [comment]
I'll close this issue, since I don't need these functions.
