### ISSUE TITLE
Next release (0.6.0)

### ISSUE THREAD

**Issue by mato** [mirage/ocaml-freestanding#77]
Several recent PRs provide new interfaces to C code downstream of ocaml-freestanding:

- #74 adds the `__ocaml_freestanding__` preprocessor macro
- #74 adds an `<endian.h>`
- #76 adds an `<inttypes.h>`

With this in mind, I think that the next release should be `0.6.0` to reflect "more than minor changes/additions", and downstream packages that wish to use these interfaces should depend on `ocaml-freestanding >= 0.6.0`.

@hannesm (`mirage-crypto` and related), @dinosaure (`hacl`), are you OK with this?

**Comment by dinosaure** [comment]
Ok with me :+1:.

**Comment by hannesm** [comment]
I just went through #76; this looks excellent (and simplifies the hacl-on-mirage by not having to modify kremlib/kremlib_base (PR https://github.com/mirage/hacl/pull/31). would be great to get this merged and released.

**Comment by mato** [comment]
One more thing, since we're cleaning up old messes -- there might be a way to resolve Solo5/solo5#456 (osreldate.h required on FreeBSD for the OCaml runtime) now rather than later:

1. Release ocaml-freestanding 0.6.0.
2. On the Solo5 side, remove osreldate.h from the CRT headers on FreeBSD, and add 
    `conflicts: [ "ocaml-freestanding" {< "0.6.0"} ]`
    to solo5-bindings-*.
3. (When it's ready, cut the next Solo5 release)

What do you think?

**Comment by mato** [comment]
(The reason this will work is because #74 undefines `__FreeBSD__`, so the problematic code in the OCaml runtime will never get compiled)

**Comment by hannesm** [comment]
@mato sounds sensible (and I just tested the change you propose [remove osreldate.h in solo5 configure.sh] locally, it works) \o/

**Comment by mato** [comment]
@hannesm Ok, sounds like a plan! Thanks for confirming.

**Comment by mato** [comment]
OPAM repository PR in ocaml/opam-repository#16368

**Comment by mato** [comment]
All done here -- including osreldate.h removal on Solo5 side in Solo5/solo5#461.
